# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batches'},
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
