# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170421_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_teacher',
        ),
    ]
