# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_authuser_is_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='name',
        ),
    ]
