# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170421_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
