# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170425_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='accounts.Teacher'),
        ),
    ]
