# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170426_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
