# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170505_0733'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set([('course', 'division', 'name')]),
        ),
    ]
