# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170425_0740'),
        ('attendance', '0002_hour_is_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHourMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='hour',
            name='subject',
        ),
        migrations.AddField(
            model_name='hour',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hour',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='subjecthourmapping',
            name='hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='attendance.Hour'),
        ),
        migrations.AddField(
            model_name='subjecthourmapping',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='attendance.Subject'),
        ),
    ]
