# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170425_0740'),
        ('attendance', '0004_auto_20170426_0413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchsubjectmapping',
            unique_together=set([('batch', 'subject')]),
        ),
        migrations.AlterUniqueTogether(
            name='batchteachermapping',
            unique_together=set([('batch', 'teacher')]),
        ),
    ]
