# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_batch_batch_teacher'),
        ('attendance', '0005_auto_20170426_0425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchsubjectmapping',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='batchsubjectmapping',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchsubjectmapping',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='batchteachermapping',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='batchteachermapping',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchteachermapping',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.Batch'),
        ),
        migrations.DeleteModel(
            name='BatchSubjectMapping',
        ),
        migrations.DeleteModel(
            name='BatchTeacherMapping',
        ),
    ]
