# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_batch_batch_teacher'),
        ('attendance', '0006_auto_20170426_0450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('name', 'batch', 'teacher')]),
        ),
    ]
