# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170426_0648'),
        ('attendance', '0009_auto_20170426_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('code', 'batch', 'teacher')]),
        ),
    ]
