# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170427_0608'),
        ('attendance', '0011_auto_20170428_0411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together=set([('student', 'date', 'code')]),
        ),
    ]
