# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170505_0923'),
        ('attendance', '0014_auto_20170428_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.Course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(choices=[('EP', 'Physics'), ('EC', 'Chemistry'), ('EM', 'Mathematics'), ('EMM', 'Mechanics'), ('ECO', 'Economical Science')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('code', 'batch', 'course')]),
        ),
    ]
