# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20170505_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, verbose_name='Name')),
                ('supertag', models.ManyToManyField(blank=True, related_name='_tag_supertag_+', to='attendance.Tag')),
            ],
        ),
    ]
