# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000, verbose_name='Title')),
                ('tag', models.ManyToManyField(blank=True, to='attendance.Tag')),
            ],
        ),
    ]
