# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='taglevel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tag level'),
        ),
    ]
