# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_auto_20170516_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
